export enum AuthEvents {
  USER_REGISTERED = 'auth.user.registered',
  USER_LOGIN = 'auth.user.login',
  USER_LOGOUT = 'auth.user.logout',
  PASSWORD_CHANGED = 'auth.password.changed',
  PASSWORD_RESET_REQUESTED = 'auth.password.reset.requested',
  PASSWORD_RESET_COMPLETED = 'auth.password.reset.completed',
  EMAIL_CHANGED = 'auth.email.changed',
  EMAIL_CHANGE_REQUESTED = 'auth.email.change.requested',
  EMAIL_VERIFIED = 'auth.email.verified',
  EMAIL_VERIFICATION_REQUESTED = 'auth.email.verification.requested',
  TWO_FACTOR_ENABLED = 'auth.2fa.enabled',
  TWO_FACTOR_DISABLED = 'auth.2fa.disabled',
  OTP_REQUESTED = 'auth.otp.requested',
  OAUTH_LINKED = 'auth.oauth.linked',
  OAUTH_REGISTER = 'auth.oauth.register',
  OAUTH_LOGIN = 'auth.oauth.login',
  NEW_DEVICE_LOGIN = 'auth.device.new',
  SESSION_REVOKED = 'auth.session.revoked',
  ACCOUNT_LOCKED = 'auth.account.locked',
  ACCOUNT_UNLOCKED = 'auth.account.unlocked',
}
