FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nx.json ./
COPY prisma ./prisma/

RUN npm ci

COPY apps ./apps
COPY libs ./libs

RUN npm run prisma:generate
RUN npm run build

FROM node:18-alpine AS production

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

ENV NODE_ENV=production

EXPOSE 4717

CMD ["node", "dist/apps/api-gateway/main.js"]
