export enum EmailEventEnum {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  NEW_DEVICE_LOGIN = 'NEW_DEVICE_LOGIN',
  OTP_CODE = 'OTP_CODE',
  APPLICATION_SENT = 'APPLICATION_SENT',
  WELCOME = 'WELCOME',
}
