export type RenderLang = 'fr' | 'de' | 'en';

export interface LabelSet {
  education: string;
  experience: string;
  skills: string;
  languages: string;
  summary: string;
  contacts: string;
  coverLetter: string;
  generatedBy: string;
}

export const I18N_LABELS: Record<RenderLang, LabelSet> = {
  fr: {
    education: 'Formation',
    experience: 'Experience',
    skills: 'Competences',
    languages: 'Langues',
    summary: 'Profil',
    contacts: 'Contact',
    coverLetter: 'Lettre de motivation',
    generatedBy: 'Genere par OstorCV',
  },
  de: {
    education: 'Ausbildung',
    experience: 'Erfahrung',
    skills: 'Kenntnisse',
    languages: 'Sprachen',
    summary: 'Profil',
    contacts: 'Kontakt',
    coverLetter: 'Anschreiben',
    generatedBy: 'Erstellt von OstorCV',
  },
  en: {
    education: 'Education',
    experience: 'Experience',
    skills: 'Skills',
    languages: 'Languages',
    summary: 'Summary',
    contacts: 'Contact',
    coverLetter: 'Cover Letter',
    generatedBy: 'Generated by OstorCV',
  },
};
